<?php


/**
 * Skeleton subclass for performing query and update operations on the 'jobeet_affiliate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/29/16 02:33:02
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetAffiliatePeer extends BaseJobeetAffiliatePeer {

} // JobeetAffiliatePeer
