<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/05/28 23:46:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
